name: vscode-json-languageserver
summary: JSON Language Server
description: |
  The JSON Language server provides language-specific smarts for editing,
  validating and understanding JSON documents. It runs as a separate
  executable and implements the language server protocol to be connected by
  any code editor or IDE.

  The server implements the following capabilities of the language server protocol:

  * Code completion for JSON properties and values based on the document's
    JSON schema or based on existing properties and values used at other
    places in the document. JSON schemas are configured through the server
    configuration options.
  * Hover for values based on descriptions in the document's JSON schema.
  * Document Symbols for quick navigation to properties in the document.
  * Document Colors for showing color decorators on values representing
    colors and Color Presentation for color presentation information to
    support color pickers. The location of colors is defined by the
    document's JSON schema. All values marked with "format": "color-hex"
    (VSCode specific, non-standard JSON Schema extension) are considered
    color values. The supported color formats are #rgb[a] and #rrggbb[aa].
  * Code Formatting supporting ranges and formatting the whole document.
  * Folding Ranges for all folding ranges in the document.
  * Semantic Selection for semantic selection for one or multiple cursor
    positions.
  * Goto Definition for $ref references in JSON schemas
  * Diagnostics (Validation) are pushed for all open documents
    * syntax errors
    * structural validation based on the document's JSON schema.

adopt-info: vscode-json-languageserver
grade: stable
confinement: strict
base: core20

layout:
  /usr/local/share/.config/yarn:
    bind: $SNAP/usr/local/share/.config/yarn

apps:
  vscode-json-languageserver:
    command: bin/vscode-json-languageserver
    plugs:
      - network
      - home

parts:
  vscode-json-languageserver:
    plugin: npm
    source: https://github.com/microsoft/vscode.git
    build-environment:
      - NODEJS_VERSION: "v20.18.0"
    npm-node-version: $NODEJS_VERSION
    # add packages so we can npm install on vscode itself as it's node
    # dependecies are needed to compile the json-languageserver
    build-packages:
      - pkg-config
      - python
      - libkrb5-dev
      - libx11-dev
      - libxkbfile-dev
      - libsecret-1-dev
      - jq
      - moreutils
    override-build: |
      # install the official nodejs so we get the expected npm version
      if [ $SNAP_ARCH == "amd64" ]; then
        ARCH=x64
      elif [ $SNAP_ARCH == "armhf" ]; then
        ARCH=armv7l
      elif [ $SNAP_ARCH == "ppc64el" ]; then
        ARCH=ppc64le
      else
        ARCH=$SNAP_ARCH
      fi
      curl -s https://nodejs.org/dist/"${NODEJS_VERSION}"/node-"${NODEJS_VERSION}"-linux-$ARCH.tar.gz | tar xzf - -C "$SNAPCRAFT_PART_INSTALL" --strip-components=1
      npm install -g yarn
      # @vscode/ripgrep fails to install behind https proxy as vscode-ripgrep
      # did - https://github.com/microsoft/vscode-ripgrep/issues/26 - and we
      # don't need it anyway for the server - same for playwright and electron -
      # also remove vscode-telemetry-extractor since this pulls in
      # vscode-ripgrep as a dependency too and is also not needed to build the
      # vscode-html-languageserver extension so is safe to remove
      jq 'del(.dependencies."@vscode/ripgrep")' package.json | sponge package.json
      jq 'del(.dependencies."@vscode/ripgrep")' remote/package.json | sponge remote/package.json
      jq 'del(.devDependencies."@vscode/telemetry-extractor")' package.json | sponge package.json
      jq 'del(.devDependencies.electron)' package.json | sponge package.json
      jq 'del(.devDependencies.playwright)' package.json | sponge package.json
      yarn why @vscode/ripgrep
      yarn global add node-gyp
      yarn install
      cd extensions/json-language-features/server
      yarn run compile
      yarn global add --prefix $SNAPCRAFT_PART_INSTALL $(yarn pack . | grep "Wrote tarball to" | cut -f2 -d'"')
      # fixup install location
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/local/share/.config
      mv /usr/local/share/.config/yarn $SNAPCRAFT_PART_INSTALL/usr/local/share/.config
      for bin in vscode-json-languageserver node-gyp; do rm $SNAPCRAFT_PART_INSTALL/bin/$bin; ln -s ../usr/local/share/.config/yarn/global/node_modules/.bin/$bin $SNAPCRAFT_PART_INSTALL/bin/$bin; done
      snapcraftctl set-version $(jq -r .version package.json)
